# Generated by Django 3.1.5 on 2021-02-22 22:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import washing_service.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, validators=[washing_service.validators.unique_brand])),
                ('car_logo', models.ImageField(blank=True, default='default-car.png', null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per wash', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Car Type',
                'verbose_name_plural': 'Car Types',
            },
        ),
        migrations.CreateModel(
            name='WashingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Washing Center',
                'verbose_name_plural': 'Washing Centers',
            },
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(help_text='Enter M/F', max_length=1, validators=[washing_service.validators.validate_gender])),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salary per order %', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
            ],
            options={
                'verbose_name': 'Washer',
                'verbose_name_plural': 'Washers',
            },
        ),
        migrations.CreateModel(
            name='ScheduledOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('phone', models.CharField(max_length=30, validators=[washing_service.validators.validate_phone])),
                ('car_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='washing_service.carbrand')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.cartype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washer')),
            ],
            options={
                'verbose_name': 'Scheduled Order',
                'verbose_name_plural': 'Scheduled Orders',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(help_text='Enter M/F', max_length=1, validators=[washing_service.validators.validate_gender])),
                ('salary', models.IntegerField(help_text='Monthly salary', validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('phone', models.CharField(max_length=30, validators=[washing_service.validators.validate_phone])),
                ('car_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='washing_service.carbrand')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.cartype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washer')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
