# Generated by Django 3.1.5 on 2021-02-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Washing Center',
                'verbose_name_plural': 'Washing Centers',
            },
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
            ],
            options={
                'verbose_name': 'Washer',
                'verbose_name_plural': 'Washers',
            },
        ),
        migrations.CreateModel(
            name='ScheduledOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=40)),
                ('car', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('phone', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washer')),
            ],
            options={
                'verbose_name': 'Scheduled Order',
                'verbose_name_plural': 'Scheduled Orders',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('car', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('phone', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washer')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
