# Generated by Django 3.1.5 on 2021-02-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='car_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
