# Generated by Django 3.1.5 on 2021-01-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0003_auto_20210127_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='scheduledorders',
            options={'verbose_name': 'Scheduled Order', 'verbose_name_plural': 'Scheduled Orders'},
        ),
        migrations.AlterModelOptions(
            name='washingcenter',
            options={'verbose_name': 'Washing Center', 'verbose_name_plural': 'Washing Centers'},
        ),
    ]
