# Generated by Django 3.1.5 on 2021-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0003_auto_20210211_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='car_logo',
            field=models.ImageField(default='default-car.png', upload_to=''),
        ),
    ]
