# Generated by Django 3.1.5 on 2021-01-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0004_auto_20210127_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
