# Generated by Django 3.1.5 on 2021-02-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0005_auto_20210211_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
