# Generated by Django 3.1.5 on 2021-01-29 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0005_auto_20210129_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter'),
        ),
        migrations.AlterField(
            model_name='scheduledorders',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washing_service.washingcenter'),
        ),
    ]
