# Generated by Django 3.1.5 on 2021-02-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0006_auto_20210212_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(max_length=20),
        ),
    ]
