# Generated by Django 3.1.5 on 2021-01-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0006_auto_20210129_0445'),
        ('washing_service', '0005_auto_20210129_0442'),
    ]

    operations = [
    ]
