# Generated by Django 3.1.5 on 2021-02-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0007_auto_20210212_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='washing_service.carbrand'),
        ),
        migrations.AddField(
            model_name='scheduledorder',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='washing_service.carbrand'),
        ),
    ]
