# Generated by Django 3.1.5 on 2021-01-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0008_auto_20210130_0243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Washer',
        ),
        migrations.AlterModelOptions(
            name='washer',
            options={'verbose_name': 'Washer', 'verbose_name_plural': 'Washers'},
        ),
    ]
