# Generated by Django 3.1.5 on 2021-02-12 18:27

from django.db import migrations, models
import washing_service.validators


class Migration(migrations.Migration):

    dependencies = [
        ('washing_service', '0009_auto_20210212_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(max_length=20, validators=[washing_service.validators.unique_brand]),
        ),
        migrations.AlterField(
            model_name='history',
            name='phone',
            field=models.CharField(max_length=30, validators=[washing_service.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='scheduledorder',
            name='phone',
            field=models.CharField(max_length=30, validators=[washing_service.validators.validate_phone]),
        ),
    ]
